version: "3.9" # optional since v1.27.0
services:
  web:
    ports:
      - "3000:3000"
    restart: "always"
    # env_file:
    #   - .env
    image: ghcr.io/asiapactalents/job-search-pwa-next:main 
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    environment:
      - REPO_USER=
      - REPO_PASSWORD=